trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '22.x'
  displayName: 'Install Node.js'

- pwsh: |
    npm install
  displayName: 'npm install'

- pwsh: |
    npm run build
  displayName: 'npm build'

- task: Docker@2
  inputs:
    containerRegistry: 'novaenglishby'
    repository: 'users'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'

- pwsh: |
    docker build --no-cache --build-arg SERVICE_NAME=users -t novaenglishby.azurecr.io/users:$(Build.BuildId) .
    docker login --username novaenglishby --password mDaRSVHmrPWUOSwYBXvj4FSVsVIuzd4NStC2JiIsu4+ACRDqtU5s
    docker push novaenglishby.azurecr.io/users:$(Build.BuildId)
  displayName: 'Build&Push Docker Image'