version: '3.9'
services:
  client-app:
    build:
      context: .
      dockerfile: apps/client-app/Dockerfile
      args:
        - CLIENT_APP_PORT=${CLIENT_APP_PORT}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - .:/usr/src/server
    ports:
      - "${CLIENT_APP_PORT}:${CLIENT_APP_PORT}"
    command: nest start client-app --watch
    networks:
      - local
    depends_on:
      - database
  users:
    env_file:
      - .env
    build:
      context: .
      dockerfile: apps/users/Dockerfile
      args:
        - USER_SERVICE_PORT=${USER_SERVICE_PORT}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    volumes:
      - .:/usr/src/server
    command: nest start users --watch
    networks:
      - local
    depends_on:
      - database
  database:
    restart: always
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: nova-platform-api
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - local
#    volumes:
#      - ./documentation/db-schema/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
volumes:
  database:
    driver: local

networks:
  local:
    driver: bridge