{{- if .Values.gateway.create }}
{{- if .Values.serviceAccounts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{.Release.Namespace}}
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.gateway.name }}
  ports:
  - name: listener
    port: {{ .Values.gateway.service.port }}
    targetPort: {{ .Values.gateway.service.targetPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
#   serviceName: {{ .Values.gateway.name }}
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.gateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gateway.name }}
    spec:
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.gateway.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      # terminationGracePeriodSeconds: 5
      # securityContext:
      #   fsGroup: 1000
      #   runAsGroup: 1000
      #   runAsNonRoot: true
      #   runAsUser: 1000
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Values.gateway.name }}
        # securityContext:
        #   runAsUser: 1000
        image: {{ .Values.images.repository }}/{{ .Values.gateway.image.name }}:{{ .Values.gateway.image.tag }}
        command: ["/bin/sh"]
        args: ["-c", "npx prisma migrate dev && npx nest start gateway --watch"]
        ports:
        - containerPort: {{ .Values.gateway.service.targetPort }}
        env:          
        {{- range $counter, $item := .Values.env }}
        - name: {{ $item.name }}
          value: "{{ $item.value }}"
        {{- end }}
        resources:
          {{- toYaml .Values.gateway.resources | nindent 10 }}
{{- end }}
