{{- if .Values.postgres.create }}
{{- if .Values.serviceAccounts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{.Release.Namespace}}
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Values.postgres.name }}
  ports:
  - name: listener
    port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.targetPort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.postgres.service.name }}
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.postgres.name }}
      {{- else }}
      serviceAccountName: default
      initContainers:
      - name: {{ .Values.postgres.name }}-init
        image: busybox
        workingDir: "/docker-entrypoint-initdb.d/"
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            ls -al
            # wget -O ddl.sql http://nginx-static-files.nova-dev.svc.cluster.local/{{.Release.Namespace}}/ddl.sql &&
            # wget -O ddl.sql http://nginx-static-files.nova-dev.svc.cluster.local/{{.Release.Namespace}}/initial-data.sql
        volumeMounts:
        - name: nova-api-postgres
          mountPath: "/docker-entrypoint-initdb.d/"
      {{- end }}
      # terminationGracePeriodSeconds: 5
      # securityContext:
      #   fsGroup: 1000
      #   runAsGroup: 1000
      #   runAsNonRoot: true
      #   runAsUser: 1000
      containers:
      - name: {{ .Values.postgres.name }}
        # securityContext:
        #   runAsUser: 1000
        image: postgres:{{ .Values.postgres.image.tag }}
        ports:
        - containerPort: {{ .Values.postgres.service.targetPort }}
        envFrom:
          {{- toYaml .Values.envFrom | nindent 12 }}
        resources:
        #   {{- toYaml .Values.postgres.resources | nindent 10 }}
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["pg_isready", "-U", {{ .Values.configmap.POSTGRES_USER | quote }}, "-d" , {{ .Values.configmap.POSTGRES_DB | quote }}]
        # livenessProbe:
        #   initialDelaySeconds: 20
        #   periodSeconds: 15
        #   grpc:
        #     port: 9555
        volumeMounts:
        - name: nova-api-postgres
          mountPath: "/docker-entrypoint-initdb.d/"
      volumes:
      - name: nova-api-postgres
{{- end }}
