# Default values for nova-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images: 
  repository: registry.novaenglish.by
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

serviceAccounts:
  # Specifies whether service accounts should be created.
  create: false
  # Annotations to add to the service accounts.
  annotations: {}

postgres:
  create: true
  name: database
  image:
    tag: 16.3-alpine
  replicas: 1
  service:
    name: database
    port: 5432
    targetPort: 5432
  resources: {}
    # requests:
    #   cpu: 200m
    #   memory: 180Mi
    # limits:
    #   cpu: 300m
    #   memory: 300Mi

gateway:
  create: true
  name: gateway
  image:
    name: nova-platform-api-gateway
  replicas: 1
  service:
    name: gateway
    port: 3000
    targetPort: 3000
  resources: {}
  #   requests:
  #     cpu: 500m
  #     memory: 800Mi
  #   limits:
  #     cpu: 900m
  #     memory: 1200Mi

rabbitmq:
  create: true
  name: rabbitmq
  image:
    tag: 4.0.1-management
  replicas: 1
  service:
    name: rabbitmq
    ports:
      - name: port
        port: 5672
        targetPort: 5672
      - name: mc-port
        port: 15672
        targetPort: 15672
  resources: {}
    # requests:
    #   cpu: 200m
    #   memory: 180Mi
    # limits:
    #   cpu: 300m
    #   memory: 300Mi

users:
  create: true
  name: users
  image:
    name: nova-platform-api-users
  replicas: 1
  service:
    name: users
    port: 3001
    targetPort: 3001
  resources: {}
    # requests:
    #   cpu: 200m
    #   memory: 400Mi
    # limits:
    #   cpu: 300m
    #   memory: 600Mi

learning:
  create: true
  name: learning
  image:
    name: nova-platform-api-learning
  replicas: 1
  service:
    name: learning
    port: 3002
    targetPort: 3002
  resources: {}
    # requests:
    #   cpu: 200m
    #   memory: 400Mi
    # limits:
    #   cpu: 300m
    #   memory: 600Mi

curriculum:
  create: true
  name: curriculum
  image:
    name: nova-platform-api-curriculum
  replicas: 1
  service:
    name: curriculum
    port: 3003
    targetPort: 3003
  resources: {}
    # requests:
    #   cpu: 200m
    #   memory: 400Mi
    # limits:
    #   cpu: 300m
    #   memory: 600Mi

envFrom:
- configMapRef:
    name: nova-env
- secretRef:
    name: nova-secret-env

configmap:
  HOST: "database"
  POSTGRES_USER: "postgres"
  DATABASE_PORT: "5432"
  POSTGRES_DB: "nova-platform-main-db-dev"
  APP_ENV: "dev"
  NODE_ENV: "development"
  FRONTEND_URL: "http://nova-front.nova-dev.svc.cluster.local/"
# - name: "GOOGLE_CALLBACK_URL"
#   value: "https://qa1.nova.local/api/v1/auth/google/callback"
  # GATEWAY_PORT: 3000
  # USER_SERVICE_PORT: 3001
  ENV_FILE: ".env.development.local"
  RABBITMQ_USER: guest
  RABBITMQ_PORT: 5672
  RABBITMQ_MC_PORT: 15672
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_URL: amqp://rabbitmq:5672
  CURRICULUM_SERVICE_PORT: 3003
  GOOGLE_CLIENT_ID: 634293760963-9e379hughfejbm4j6093mpoi2s6btsos.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  GOOGLE_CALLBACK_URL: http://localhost:3000/api/v1/auth/google/callback
  JWT_SECRET: supersecuresecret

secrets:
  POSTGRES_PASSWORD: "randompassword"
  RABBITMQ_PASSWORD: guest
