name: Deploy to nova-qa3

on: workflow_dispatch

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v4.0.1
        with:
          exec: helm upgrade --install nova-api helm/ -n nova-qa3
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          # overrule_existing_kubeconfig: "true"
