name: Deploy to nova-qa3

on: workflow_dispatch

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'nova-api'
          track: canary
          namespace: 'nova-qa3'
          chart: 'helm'
          # token: '${{ github.token }}'
          # values: |
          #   name: foobar
          value-files: >-
            [
              "helm/values.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'