name: Build Images

on:
  # manual run
  workflow_dispatch:

  # push:
  #   branches: [main]

  # pull_request:
  #   branches: [main]

env:
  REGISTRY: registry.novaenglish.by

jobs:
  build:

    strategy:
      matrix:
        service: ['gateway', 'learning', 'users']

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: apps/${{ matrix.service }}/Dockerfile
          tags: ${{ env.REGISTRY }}/nova-platform-api-${{ matrix.service }}:${{ steps.slug.outputs.sha7 }}
