name: Build Images

on:
  # manual run
  workflow_dispatch:

  # push:
  #   branches: [main]

  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to the Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.novaenglish.by
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: apps/gateway/Dockerfile
          tags: registry.novaenglish.by/nova-platform-api-gateway:latest
