name: Build Images

on:
  # manual run
  workflow_dispatch:

  # push:
  #   branches: [main]

  # pull_request:
  #   branches: [main]

jobs:
  build:

    strategy:
      matrix:
        service: ['gateway', 'learning', 'users']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to the Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.novaenglish.by
      #     username: ${{ vars.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}) | tr '/'" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: apps/${{ matrix.service }}/Dockerfile
          tags: registry.novaenglish.by/nova-platform-api-${{ matrix.service }}:${{ steps.extract_branch.outputs.branch }}
