# name: Node.js CI

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - name: Use Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '22.6.x'
#       - run: npm install
#       - run: npm install -g @nestjs/cli
# #      - run: npm install -g vitest
# #      - run: vitest --pass-with-no-tests
#       - run: nest build
# #      - run: npm run build --if-present
      
#       - name: Archive production artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: dist-without-markdown
#           path: |
#             dist
# #            !dist/**/*.md
